name: gnn_project
channels:
  - pyg
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - networkx
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - matplotlib
  - cartopy=0.21.1
  - jupyter
  - pyg
